export const products=[
    {
        id:1,
        img:"https://img.freepik.com/free-psd/website-instant-showcase-mockup-isolated_359791-227.jpg?w=2000",
        link:"https://pankaj.com"
    },
    {
        id:2,
        img:"https://mobirise.com/assets52/images/features1.jpg",
        link:"https://pankaj.com"
    },
    {
        id:3,
        img:"https://img.freepik.com/free-psd/website-instant-showcase-mockup-isolated_359791-227.jpg?w=2000",
        link:"https://pankaj.com"
    },
     {
        id:4,
        img:"https://mobirise.com/assets52/images/features1.jpg",
        link:"https://pankaj.com"
    },
    {
        id:5,
        img:"https://img.freepik.com/free-psd/website-instant-showcase-mockup-isolated_359791-227.jpg?w=2000",
        link:"https://pankaj.com"
    },
    {
        id:6,
        img:"https://mobirise.com/assets52/images/features1.jpg",
        link:"https://pankaj.com"
    }
]